### PR TITLE
[WIP] debug, don't merge! 

### PR DESCRIPTION
**Pull request by lgarithm**

### CODE REVIEW

**Comment by DEKHTIARJonathan** [comment]
@lgarithm you dont need to precise **dont merge**. If "WIP" is in the title, merging is blocked ;)

I have set the branch **debug-ci** to build on RTD: https://readthedocs.org/projects/tensorlayer/builds/7442938/

You can check than the branch is building fine before merging ;)

**Comment by lgarithm** [comment]
@DEKHTIARJonathan great, thank!

I'm using this PR just for triggering travis CI, I reduced the CI matrix for quicker run in it.

**Comment by DEKHTIARJonathan** [comment]
@lgarithm I'm not sure having Firebug to create an issue for every build to be a good idea... 
We are spamming everyone following the project ...

**Comment by lgarithm** [comment]
How about make it [send email to slack](https://get.slack.help/hc/en-us/articles/206819278-Send-emails-to-Slack).

**Comment by lgarithm** [comment]
Currently it only supports sending directly message to me from slackbot.
Ideally it should be send to a channel.

**Comment by DEKHTIARJonathan** [comment]
@lgarithm fully agree with slack, we can create a channel specific for build infos ;)

**Pull request closed without merging**
