### PR TITLE
cache pip for faster CI build

### PR DESCRIPTION
**Pull request by lgarithm**
Currently `pip install` takes about 90s out of 3m30s per build.

### CODE REVIEW

**Comment by DEKHTIARJonathan** [comment]
Does it actually works? I tried to do it but never succeeded 😅

**Comment by lgarithm** [comment]
Not yet, maybe some additional steps are required:
https://docs.travis-ci.com/user/caching/#before_cache-phase
Or maybe this needs to be on master to make it work for later CIs.

**Comment by lgarithm** [comment]
Basically I'd like to cache the `.whl` files downloaded by pip.
I need to make sure they are stored in `$HOME/.cache/pip`.

**Comment by lgarithm** [comment]
@luomai @DEKHTIARJonathan I think the cache is working now.
`pip install` is using cache and the time it takes reduced to 45s from 90s.

**Comment by DEKHTIARJonathan** [comment]
Fine with me I merge 😊

**Pull request merged**
