### PR TITLE
refactoring: Deduplication

### PR DESCRIPTION
**Pull request by marload**
### Checklist
- [ ] I've tested that my changes are compatible with the latest version of Tensorflow.
- [ ] I've read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context

Duplicate code is not good for maintenance.

### Description

Duplicate code removed.

### CODE REVIEW

**Comment by JingqingZ** [comment]
Not sure what has happened. It seems CI's report didn't return back, though it should have passed.

**Comment by lgarithm** [comment]
I've requested a rebuild on travis-ci (https://travis-ci.org/github/tensorlayer/tensorlayer/builds/696471153), hope it would return status soon.

**Comment by marload** [comment]
One of the tests doesn't seem to work.

**Comment by Laicheng0830** [comment]
thank u! can be merged

**Pull request merged**
