### PR TITLE
remove graph api

### PR DESCRIPTION
**Pull request by zsdonghao**
### Motivation and Context
- Remove graph API
- Unitest for timeout

### CODE REVIEW

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao I have edited your post. I will merge this PR once we have a unittest to highlight the issue.

**Comment by zsdonghao** [comment]
@DEKHTIARJonathan I already add the unitest in this PR.

**Comment by zsdonghao** [comment]
@DEKHTIARJonathan I have no idea why the style test will fail ..

**Comment by DEKHTIARJonathan** [comment]
image

I'm gonna have a look

**Pull request merged**
