### PR TITLE
New release

### PR DESCRIPTION
**Pull request by zsdonghao**
### Checklist
- [x] I've tested that my changes are compatible with the latest version of Tensorflow.
- [x] I've read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
- [x] fix nltk lazy import
- [x] fix cv2 lazy import

### CODE REVIEW

**Comment by luomai** [comment]
Have you tested on a clean machine to see if this has resolved the issue?

**Comment by zsdonghao** [comment]
@luomai it is solved, I tested.

**Comment by luomai** [comment]
@zsdonghao Thanks!

**Comment by zsdonghao** [comment]
As it is `rc` version, it would not be shown as stable version on online docs, we should set readthedocs to show latest version, right?

**Pull request merged**
