### PR TITLE
[WIP] Fix Issue #561 - Convolution Support NCHW

### PR DESCRIPTION
**Pull request by 2wins**
### Checklist
- [x] I've tested that my changes are compatible with the latest version of TensorFlow.
- [x] I've read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context

Issue #561 

### Description

- [x] `Conv1dLayer`
- [x] `Conv2dLayer`
- [ ] `DeConv2dLayer`
- [x] `Conv3dLayer`
- [ ] `DeConv3dLayer`
- [ ] `UpSampling2dLayer`
- [ ] `DownSampling2dLayer`
- [ ] `DeformableConv2d`
- [ ] `AtrousConv1dLayer`
- [ ] `AtrousConv2dLayer`
- [ ] `deconv2d_bilinear_upsampling_initializer`
- [x] `Conv1d`
- [x] `Conv2d`
- [ ] `DeConv2d`
- [ ] `DeConv3d`
- [ ] `DepthwiseConv2d`
- [ ] `SeparableConv1d`
- [ ] `SeparableConv2d`
- [ ] `GroupConv2d`

### CODE REVIEW

**Comment by DEKHTIARJonathan** [comment]
@2wins It is a good thing that you thought about creating a unittest file.
I was wondering, don't you think that the most efficient and simplest way is to duplicate the file `test_layers_convolution.py` and create:
- `test_layers_convolution_channel_first.py`
- `test_layers_convolution_channel_last.py`

The exact same code just switching the position of the channnel dimension and adapting the tests.

**Comment by 2wins** [comment]
@DEKHTIARJonathan It was not appropriate to duplicate `test_layers_convolution.py` directly because here `data_format` problem does not require output for testing. Anyway, as you said, I think dividing the file into two files are better.
Meanwhile, I found that `Conv*dLayer` using `tf.nn.conv*d` had problems. I think `tf.nn.conv*d` must not be affected by `shape` parameter but different `data_format` has an impact on `shape`.

**Comment by DEKHTIARJonathan** [comment]
@2wins I'm not sure to understand your point ;)

The objective of having the "same" file, modified accordingly to the position of the channel layer is not really about testing the output shape. The output shape can be seen as a sanity check ;)

No the rpincipal objective of the convolution test file is to be sure that no error is generated during the graph definition.

Thus, up to me, it is perfectly relevant to have the exact same file modified to use a the channel first data format. 

Could you please explain a bit more why you think it's not appropriate, I may have missed smthg.

Thanks buddy

**Comment by 2wins** [comment]
@DEKHTIARJonathan I agree with you. After no error on graph definition, sanity check is essential. I missed the important point. Thanks.

**Comment by DEKHTIARJonathan** [comment]
May you add me as a contributor to your fork ?
I would like to be able to help you directly. You started some quite heavy changes, you may want some help ;)

**Comment by 2wins** [comment]
@DEKHTIARJonathan Of course! please help me a lot. Plus, please let me join the Slack :cry:.

**Comment by DEKHTIARJonathan** [comment]
We do our best regarding the slack account. Do you have any alternative email ?

**Comment by 2wins** [comment]
@DEKHTIARJonathan I tried it with other email accounts but failed all.

**Comment by DEKHTIARJonathan** [comment]
The CircleCI builds were not activated for forked PR this has been fixed and this PR will be build when a new commit will be pushed ;)

**Comment by DEKHTIARJonathan** [comment]
@2wins How is this PR going so far ? U need help ?

**Comment by 2wins** [comment]
@DEKHTIARJonathan Yes, I think I need some help. As I mentioned before, the current `data_format`s in TensorFlow are very inconsistent, e.g. some operations uses `channels_first/last` while others `NCHW (NHWC)` . Moreover, the convolution operations (or layers) seem to be affected by weight variables' `shape`. I think we'd better support only `channels_last`, `NHWC` (default `data_format`) for the time being.
What do you think of it?

**Comment by zsdonghao** [comment]
@2wins I agree with you, `channels_last` is easier for users.

**Comment by 2wins** [comment]
@DEKHTIARJonathan @zsdonghao  Do you have any python techniques for mapping a word (string) into another one? I think it's a top priority to support consistent `data_format`.

**Comment by DEKHTIARJonathan** [comment]
I'm not sure to understand what you want to do

**Comment by 2wins** [comment]
@DEKHTIARJonathan Actually, if we want to provide two kinds of `data_format`s, then we allow users use consistent arguments e.g. only `channel_last/first` instead of `NCHW/NHCW`, or both of them. At that time, string mapping techniques are needed.
If we only support the argument `channel_last` (`NHWC`), we don't need such processing because a user don't put a argument into it and we just handle `data_format` internally.

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao can I let you handle this PR ?

**Comment by 2wins** [comment]
@DEKHTIARJonathan As seen in @zsdonghao 's last comments, we can handle this issue by removing `data_format` and just using the argument set to `channels_last` internally.

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao @2wins shall I close this PR ?

**Comment by 2wins** [comment]
> @DEKHTIARJonathan Actually, if we want to provide two kinds of `data_format`s, then we allow users use consistent arguments e.g. only `channel_last/first` instead of `NCHW/NHCW`, or both of them. At that time, string mapping techniques are needed. (Some convs in TF take `channel_last/first` while others do `NCHW/NHCW`)
> If we only support the argument `channel_last` (`NHWC`), we don't need such processing because a user don't put an argument into it and we just handle `data_format` internally.



> @DEKHTIARJonathan As seen in the @zsdonghao 's last comment, we can handle this issue by removing `data_format` and just using the argument set to `channels_last` internally.

@DEKHTIARJonathan, @zsdonghao As I said before, many conv layers are inconsistent in terms of argument `data_format`. Some of them take `NCHW/NHWC` and others do `channels_first/channels_last`. Meanwhile, some do not have `data_format` and process features (tensors) in a `NHWC/channels_last` way internally. We have to discuss it.

**Comment by zsdonghao** [comment]
It seen TF will use `channel_last/first` to replace all `NCHW/NHCW`,  we can follow them.

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao @2wins All right. Let's do this. I close this PR, we will follow this trend in PR #755 ;)

**Pull request closed without merging**
