### PR TITLE
PyUP and Stale Bot Configuration Updated

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
No Update of the Changelog is required, it is already updated.
You can directly merge ;)

### CODE REVIEW

**Comment by DEKHTIARJonathan** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry. <br />
You can find it at <a href="https://github.com/tensorlayer/tensorlayer/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Note, we hard-wrap at 80 chars and use 2 spaces after the last line.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lgarithm** [comment]
Should we remove the message from danger?
`Note, we hard-wrap at 80 chars and use 2 spaces after the last line.`

I think it's just an example of how to use danger message.

**Comment by DEKHTIARJonathan** [comment]
@lgarithm if you want to ;) To me it doesn't change much. I let you open a PR if you want, I will approve it.

**Comment by lgarithm** [comment]
Ok, just leave it as it is for now.

________________________________

**Pull request merged**
