### PR TITLE
Update load file list -- enable keeping path in the file name

### PR DESCRIPTION
**Pull request by zsdonghao**
### Checklist
- [x] I've tested that my changes are compatible with the latest version of Tensorflow.
- [x] I've read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

Update load file list -- enable keeping path in the file name

### CODE REVIEW

**Comment by DEKHTIARJonathan** [comment]
Why using regex which is a pain and not simply the `glob` package already present in python that does this job very nicely ?

**Comment by zsdonghao** [comment]
i see, we can use `glob` then

**Comment by zsdonghao** [comment]
@DEKHTIARJonathan but we could merge this one first, it would not effect the previous codes.

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao As soon as you have updated the changelog, I will merge ;)

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao I merged and I let you implement glob when you have time ;)

**Pull request merged**
