### PR TITLE
Tutorial fixing

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
This PR aims to insure that all the tutorial are working fine and nicely.

This PR solve the following bugs:
- Issue #476 with model saving in tutorial_word2vec
- `tf.flags` changed for `tf.app.flags`
- various bugs in all files fixed

Tested Tutorials:
- [x] tutorial_atari_pong.py
- [x] tutorial_binarynet_cifar10_tfrecord.py
- [x] tutorial_binarynet_mnist_cnn.py
- [ ] tutorial_bipedalwalker_a3c_continuous_action.py => **FAILING**
- [x] tutorial_cartpole_ac.py
- [x] tutorial_cifar10.py
- [x] tutorial_cifar10_tfrecord.py
- [x] tutorial_dorefanet_cifar10_tfrecord.py
- [x] tutorial_dorefanet_mnist_cnn.py
- [x] tutorial_frozenlake_dqn.py
- [x] tutorial_frozenlake_q_table.py
- [x] tutorial_generate_text.py
- [ ] tutorial_imagenet_inceptionV3_distributed.py => **Not tested yet**
- [x] tutorial_image_preprocess.py
- [x] tutorial_imdb_fasttext.py
- [x] tutorial_inceptionV3_tfslim.py
- [x] tutorial_keras.py
- [x] tutorial_matrix.py
- [x] tutorial_mlp_dropout1.py
- [x] tutorial_mlp_dropout2.py
- [x] tutorial_mnist.py
- [ ] tutorial_mnist_distributed.py => **Not tested yet**
- [x] tutorial_mnist_float16.py
- [x] tutorial_mnist_simple.py
- [x] tutorial_mobilenet.py
- [x] tutorial_models_mobilenetv1.py
- [x] tutorial_models_squeezenetv1.py
- [x] tutorial_models_vgg16.py
- [x] tutorial_ptb_lstm.py
- [x] tutorial_ptb_lstm_state_is_tuple.py
- [x] tutorial_squeezenet.py
- [x] tutorial_ternaryweight_cifar10_tfrecord.py
- [x] tutorial_ternaryweight_mnist_cnn.py
- [x] tutorial_tfrecord.py
- [x] tutorial_tfrecord2.py
- [x] tutorial_tfrecord3.py
- [x] tutorial_tfslim.py
- [x] tutorial_tf_dataset_voc.py
- [x] tutorial_vgg16.py
- [x] tutorial_vgg19.py
- [x] tutorial_word2vec_basic.py

### CODE REVIEW

**Comment by zsdonghao** [comment]
Hi, `tl.files.save_npz` with `sess=sess` works fine now?

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao Nope, I have just applied your workaround.
And I also modified a few errors I have noticed in the tutorials. I will check that all of them run fine.

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao Tutorial VGG16 is not working, can't load the checkpoint.
I have cleaned it a little but still not working, you can checkout the branch of this PR if you want ;)

**Comment by zsdonghao** [comment]
@DEKHTIARJonathan I update the vgg16 tutorial with auto model download~

**Comment by zsdonghao** [comment]
it can be merged now

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao some tutorials are still failing. I would prefer testing everything before

**Comment by zsdonghao** [comment]
for `tutorial_tf_dataset_voc.py` is seem there is a problem on the VOC website...

http://host.robots.ox.ac.uk/pascal/VOC/voc2007/

http://host.robots.ox.ac.uk/pascal/VOC/voc2012/

We can try later?

**Comment by zsdonghao** [comment]
for `tutorial_generate_text.py`, I try in on my mac, it works well:

```
Start learning a model to generate text
Epoch: 1/100 Learning rate: 1.00000000
0.002 perplexity: 8721.404 speed: 2486 wps
0.100 perplexity: 1586.901 speed: 3974 wps
0.199 perplexity: 1021.575 speed: 4101 wps
0.297 perplexity: 766.037 speed: 4146 wps
0.395 perplexity: 625.603 speed: 4162 wps
0.493 perplexity: 533.806 speed: 4164 wps
0.592 perplexity: 481.060 speed: 4146 wps
0.690 perplexity: 439.476 speed: 4109 wps
0.788 perplexity: 404.770 speed: 4090 wps
0.886 perplexity: 375.800 speed: 4086 wps
0.985 perplexity: 352.464 speed: 4080 wps
Epoch: 1/100 Train Perplexity: 350.236
1 : it is a long time , and i would like that . we can not do that . we can not do that . we can not do that . we can not
3 : it is a much , but the fact is , we will make a new new jobs . we need a deal to be a long time , and i want to the
5 : it is a much for the new york . the way , the fact , i want a great time , and i had it to do , the way , and i
10 : it is a long , a lot of a lot to the oil , but a good , the world would not be the “ . ” would like the obama , and

...
```

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao there was an error with Unicode and Python3, I just fixed it and now it's working.

Only 4 tutorials to fix and 2 to more to test.

**Comment by DEKHTIARJonathan** [comment]
`tutorial_tf_dataset_voc.py` fixed thanks to #657

**Comment by DEKHTIARJonathan** [comment]
Error with `python tutorial_ternaryweight_cifar10_tfrecord.py`:

```python
 File "tutorial_ternaryweight_cifar10_tfrecord.py", line 195, in <module>
    network, cost, acc, = model(x_train_batch, y_train_batch, False)
  File "tutorial_ternaryweight_cifar10_tfrecord.py", line 166, in model
    net = tl.layers.TernaryConv2d(net, 64, (5, 5), (1, 1), act=tf.nn.relu, padding='SAME', name='cnn2')
  File "e:\git projects\tensorlayer\tensorlayer\deprecation.py", line 24, in wrapper
    return f(*args, **kwargs)
  File "e:\git projects\tensorlayer\tensorlayer\layers\binary.py", line 535, in __init__
    data_format=data_format
  File "E:\Git Projects\tensorlayer\venv\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1042, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "E:\Git Projects\tensorlayer\venv\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 528, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'input' to a tensor and failed. Error: None values not supported.
```

**Comment by DEKHTIARJonathan** [comment]
@luomai and myself agreed to merge and fix later the 3 remaining tests

**Pull request merged**
