### PR TITLE
add setlinebuf helper function and call it in distributed example

### PR DESCRIPTION
**Pull request by lgarithm**

### CODE REVIEW

**Comment by jorgemf** [comment]
I notice this issue too. I also read the normal behavior in Linux is to buffer the output (it sounds strange for me but I bought it). My solution was to use the logging package for printing more info and to configure it to flush the output more often. I am working on another example that does this, once I am completely sure it works I will do the PR (also fix other bugs in the distributed mode).

**Comment by zsdonghao** [comment]
@luomai could you help to review it?

BTW, to add new API to the documentation, see `docs/modules/xxx.rst`.

**Comment by jorgemf** [comment]
Another way to unbuffer the python output is to set the environment variable `PYTHONUNBUFFERED=1`. So we don't need to touch any code

**Comment by luomai** [comment]
@jorgemf totally agree. A more fundamental solution would be to use logger instead of print in, at least, the distributed and docker examples.

**Comment by lgarithm** [comment]
yes, and I think the best place to add it is in the Dockerfile.

**Pull request merged**
