### PR TITLE
Update more.rst

### PR DESCRIPTION
**Pull request by 2wins**
Update the URLs

### Checklist
- [x] I've tested that my changes are compatible with the latest version of Tensorflow.
- [x] I've read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Wrong or old links

### Description

Update URLs

### CODE REVIEW

**Comment by 2wins** [comment]
@DEKHTIARJonathan Do you mean that the FAQ page is no longer updated?

**Comment by DEKHTIARJonathan** [comment]
Look at Travis or launch PyTest.
You will see the documentation is failing

**Comment by 2wins** [comment]
@DEKHTIARJonathan it has passed PyTest. Please merge it. Thank you.

**Comment by 2wins** [comment]
@DEKHTIARJonathan It's my mistake. Please check and merge it.

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao can you please have a look and merge if it looks good.
I'm not very good in RST, I don't want to make any mistake ;)

**Pull request merged**
