### PR TITLE
matplotlib.use('TkAgg')

### PR DESCRIPTION
**Pull request by lgarithm**
### Checklist
- [X] I've tested that my changes are compatible with the latest version of Tensorflow.
- [X] I've read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by luomai** [comment]
Please update the CHANGELOG @lgarithm

**Comment by DEKHTIARJonathan** [comment]
Do you think you can add some code to only run this change under Mac OS?

I would prefer not having a bug fix which affects everyone if not necessary 😉

**Comment by lgarithm** [comment]
@DEKHTIARJonathan I tested it on mac, it's working. Thanks for the fix!

**Comment by DEKHTIARJonathan** [comment]
the point of an RC release is to check that everything works as expected without any bug. if we just add a bug fix. we dont need an rc release in my opinion

**Pull request merged**
