### PR TITLE
update install instruction

### PR DESCRIPTION
**Pull request by lgarithm**
Instruct user to use a faster command to install the latest TL.
No code change, no changelog is required.

### CODE REVIEW

**Comment by lgarithm** [comment]
It only downloads 5MB instead of 100MB+.

**Comment by DEKHTIARJonathan** [comment]
Some issue appeared with Travis, I'll merge as soon as it pass. I tried to relaunch the failed jobs.

**Comment by DEKHTIARJonathan** [comment]
@lgarithm your PR is bugged ... I don't know the issue ... Travis can't manage to build ... This doesn't make any sense as you haven't modify any code ...

**Comment by lgarithm** [comment]
trying in a new PR #859

**Pull request closed without merging**
