### PR TITLE
[WIP] Include Danger in travis-ci

### PR DESCRIPTION
**Pull request by lgarithm**
### Checklist
- [x] I've tested that my changes are compatible with the latest version of Tensorflow.
- [x] I've read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context
#562
Some new textSome new text

### CODE REVIEW

**Comment by lgarithm** [comment]
Let's see how it works for a PR.

**Comment by lgarithm** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry. <br />
You can find it at <a href="https://github.com/tensorlayer/tensorlayer/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Note, we hard-wrap at 80 chars and use 2 spaces after the last line.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lgarithm** [comment]
Looks like it's working.

And according to our settings, failed to pass danger check won't block merge.
screen shot 2018-05-11 at 11 43 27 pm

**Comment by lgarithm** [comment]
The remaining thing TODO is just introduce the CHANGELOG.md file, 
and rewrite Dangerfile appropriately.

**Comment by lgarithm** [comment]
@luomai the danger check provides a way of running additional checks within travis-ci. 
We were searching for such a solution (a way to add warning message in test, but not fail to test.) when fixing pylints.

**Comment by DEKHTIARJonathan** [comment]
@lgarithm I have added a template for the Changelog.md

I will update it with the relevant information for the 1.8.5 release

**Comment by lgarithm** [comment]
## Danger has errored
[!] Invalid `Dangerfile` file: undefined local variable or method `prose` for #\<Danger::Dangerfile:0x00000001656ed0\>
Did you mean?  parse
               proc
```
 #  from Dangerfile:8
 #  -------------------------------------------
 #  # Look for prose issues
 >  prose.lint_files markdown_files
 #  
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lgarithm** [comment]
## Danger has errored
[!] Invalid `Dangerfile` file: undefined local variable or method `prose` for #\<Danger::Dangerfile:0x00000002615100\>
Did you mean?  parse
               proc
```
 #  from Dangerfile:8
 #  -------------------------------------------
 #  # Look for prose issues
 >  prose.lint_files markdown_files
 #  
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lgarithm** [comment]
## Danger has errored
[!] Invalid `Dangerfile` file: undefined local variable or method `markdown_files` for #\<Danger::Dangerfile:0x000000014c68b8\>
```
 #  from Dangerfile:8
 #  -------------------------------------------
 #  # Look for prose issues
 >  prose.lint_files markdown_files
 #  
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lgarithm** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry. <br />
You can find it at <a href="https://github.com/tensorlayer/tensorlayer/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Note, we hard-wrap at 80 chars and use 2 spaces after the last line.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao we should try a merge. It seems that we need to have the Changelog inside the repository for it to work.

Is it fine if I merge and we'll see if it works ?

**Comment by DEKHTIARJonathan** [comment]
After a talk with @zsdonghao I merge this PR

**Comment by 2wins** [comment]
@DEKHTIARJonathan This PR seems to have a problem. Any PR cannot pass the Travis-CI test now.

**Comment by DEKHTIARJonathan** [comment]
Problem with API key I'll fix it tonight. I don't have my computer now

**Pull request merged**
