### PR TITLE
Deprecation warning fixes - Related to issue #479

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
All the details related to this PR can be found in issue #479.

Please proof-read and test the PR before merging. I hope I didn't break anything in the process ;)

Thanks a lot,

Jonathan

### CODE REVIEW

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao : damned, I just spent two hours correcting this :(

I do my best to re-modify all of this and then update this PR

**Comment by zsdonghao** [comment]
@DEKHTIARJonathan wait a moment, let me discuss with @lgarithm and @luomai first ..

**Comment by luomai** [comment]
@DEKHTIARJonathan Thanks for the PR. Really appreciate it.
I am discussing with @zsdonghao  and @lgarithm to figure out the best way to resolve the `layer` vs `prev_layer`. The other deprecation fixes look good to us. 

In the long term, providing these two key-based input parameters would confuse users. We prefer keeping either one of them. We are open for switching back to the `layer`. However, we need to discuss with other TL users to see if they have switched to `prev_layer` already, and they may complain why we change back.

This change was included TL 1.7 which is a maintenance release released in the January. TL 1.7 resolves many technical debts and we expected some of the API might breaks. We are very sorry about for your experience. At that time, we are also conservative about the release and 1.7 gone through a pre-release stage for public feedbacks.

Thanks again for your contribution.

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao @luomai thanks a lot for your feedback, I finish this PR. A few errors are still present, then it will be easier to fix it ;)

In anyway, I think it is of good practice to not "just removed" something, and first put a deprecation warning. My complaint wasn't about "why did you do it" but more about the way it is conducted. However, I must admit I don't really understand why it was changed and would be fine with a rollback on the name of this argument.

**Comment by lgarithm** [comment]
I think the first argument of `Layer` should be passed as positional argument instead of keyword argument (we should fix our code to follow that convention too), in that case, the name of the first argument (`layer` or `prev_layer`) becomes an internal concept, and it shouldn't appear at the caller.

**Comment by DEKHTIARJonathan** [comment]
I would say it depends on your coding practice, I tend to precise all of the arguments. Much easier to read a while later and I am sure to be robust to any unwanted API change and detect it.

Information: I finally fixed my PR. Now **layer** and **prev_layer** are both working. **layer** argument send a deprecated warning

**Comment by luomai** [comment]
Hi @DEKHTIARJonathan we have extensively discussed the PR and tested it with the TL users at Imperial College London. We find that this PR could break some of their programs if they are using position-based argument to specify the input layer instead of the key-based. Given this, we considering merging your PR into a `back-support` branch and let the specific users to install it by themselves.

If this PR contains other commits for the deprecation issues 2,3,4 in #479, would you mind submitting them in separated PRs?

Again, we are all appreciated of your time in looking into this and coming up with this PR. We will take the reported issue as a lesson and would try best to avoid it in the future. Thanks for your contribution again! :)

cc: @zsdonghao @lgarithm

**Comment by DEKHTIARJonathan** [comment]
I have implemented a solution based on this simple idea, I am currently updating all my modifications.

I implemented a custom decorator that handle renaming for both functions and methods.
This has the advantages of just providing an alias to arguments, not adding any argument and not changing the order.

```python
import functools
import warnings
import logging


def deprecated_alias(end_support_version, **aliases):

    def deco(f):
	
        @functools.wraps(f)
        def wrapper(*args, **kwargs):
			
            try:
                func_name = "{}.{}".format(args[0].__class__.__name__, f.__name__)
            except (NameError, IndexError):
                func_name = f.__name__
			
            rename_kwargs(
				kwargs, 
				aliases, 
				end_support_version,
				func_name
			)
			
            return f(*args, **kwargs)

        return wrapper

    return deco


def rename_kwargs(kwargs, aliases, end_support_version, func_name):

    for alias, new in aliases.items():
	
        if alias in kwargs:
		
            if new in kwargs:
                raise TypeError('{} received both {} and {}'.format(func_name, alias, new))

            warnings.warn('{} is deprecated; use {}'.format(alias, new), DeprecationWarning)
            logging.warning("DeprecationWarning: {}(): "
                            "`{}` argument is deprecated and will be removed in {},"
                            "please change for `{}`".format(func_name, alias, end_support_version, new))
            kwargs[new] = kwargs.pop(alias)
			

class MyClass(object):

    @deprecated_alias(object_id='id_object', end_support_version=1.6)
    def __init__(self, id_object):
        self.id = id_object
        
        print("I am object: %d" % self.id)

@deprecated_alias(name='username', end_support_version=1.6)		
def yolo(username):
	print("YOLLLOOOOOOO %s" % username)

if __name__ == "__main__":

	object1 = MyClass(object_id=1234)
	object2 = MyClass(id_object=1234)
	
	print()
	
	yolo(username="John")
	yolo(name="John")
```

**Comment by DEKHTIARJonathan** [comment]
With the commit 8ea85df I have finished implementing this idea.

You can now run this code seemlessly:

```python
import tensorflow as tf
import tensorlayer as tl

x = tf.placeholder("float32", [None, 100])

input = tl.layers.InputLayer(x, name='in')

out1 = tl.layers.DenseLayer(input, 80, name='h1')
out2 = tl.layers.DenseLayer(prev_layer=input, n_units=80, name='h2')
out3 = tl.layers.DenseLayer(layer=input, n_units=80, name='h3')
```

The new solution should address every situations ;)

**Comment by zsdonghao** [comment]
@DEKHTIARJonathan @luomai @lgarithm lets join slack~~

**Comment by luomai** [comment]
@wagamamaz a friendly ping, in case you are also interested in joining the Slack channel.

**Comment by DEKHTIARJonathan** [comment]
@zsdonghao thanks a lot, I was already on slack. It is pretty inactive, is there any private channel where you discuss with the development team?

**Comment by zsdonghao** [comment]
hi, @DEKHTIARJonathan  we have a private channel in slack , and we just invite you

**Pull request merged**
