### PR TITLE
[WIP] remove depencendy on matplotlib

### PR DESCRIPTION
**Pull request by lgarithm**
### Checklist
- [X] I've tested that my changes are compatible with the latest version of Tensorflow.
- [V] I've read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Description

TODO: 
* [ ] use `save_image` for `visualization` in `tsne_embedding`.

### CODE REVIEW

**Comment by zsdonghao** [comment]
@lgarithm `tsne_embedding` is important, could we use `save_image` to do the visualisation?

**Comment by lgarithm** [comment]
@zsdonghao Sure.
I know this change will remove some important function, so please review carefully.

**Comment by DEKHTIARJonathan** [comment]
Why did u remove everything and not set the dependency as optional. I don't understand

**Comment by zsdonghao** [comment]
@DEKHTIARJonathan i think these APIs can be removed except the TSNE one.

**Comment by DEKHTIARJonathan** [comment]
@lgarithm is it really necessary now to remove all these functions ? Now that we don't need any dependency for the documentation ?

**Comment by lgarithm** [comment]
@DEKHTIARJonathan Since we've fixed RTD, this PR is not urgent ATM.
But I still think we should remove depencendy on matplotlib as part of TL2.0.
I think TL should focus on **layers,** **models** and **networks,** visualization is not a key feature of TL.

**Comment by DEKHTIARJonathan** [comment]
Can we close this @lgarithm, this PR is stalled and it does not seem to be a short term objective ;)

**Pull request closed without merging**
